import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageSelector from "@/components/language-selector"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "b4b",
  description: "Generated by create next app",
  icons: {
    icon: "/lexend_icon_svg.svg",
    shortcut: "/lexend_icon_svg.svg",
    apple: "/lexend_icon_svg.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Language selector precisely aligned to the responsive logo's vertical center */}
        {/* Further vertical alignment refinement to center the selector on the logo */}
        <div className="fixed top-[35px] right-6 sm:right-10 lg:top-[40px] lg:right-32 z-50">
          <LanguageSelector />
        </div>
        {children}
      </body>
    </html>
  );
}
